### ISSUE TITLE
Custom Farming: Be able to craft non-placeable items. 

### ISSUE THREAD

**Issue by shailalias** [Platonymous/Stardew-Valley-Mods#12]
Example: In the crafting menu, we can create the field snack, which can be used for other purposes, or consumed.

 I would like to be able to create a custom crafted item that can then be placed in a custom machine. The crafted item could use a current object id, just as the custom machines use for their produce. 

Obviously, I could use the original object as the starter material for the custom machine, but this is mostly for thematic purposes. Right now, my only solution (from what I can tell) is to create two machines. However, I'd rather avoid that. 

I hope my explanation makes sense. If not, I can clarify further.

**Comment by Platonymous** [comment]
Spacechase0's upcoming replacement for Custom Crops, called Json Assets, will allow for that and the next version of Custom Farming will fully support Json Asset objects.
