### ISSUE TITLE
Animal happiness/eating not working properly

### ISSUE THREAD

**Issue by vaindil** [Platonymous/Stardew-Valley-Mods#14]
This is being caused by either the toolkit or by No Soil Decay Redux, I haven't had a chance to test which of the two it is (can do so later today). Another user was having the same issue as me and he narrowed it down to one of these two.

I have a chicken and its happiness is always set at 0 with the offending mod. The animal is also marked as not having eaten even though it has. I worked with several other people for this issue and I am certain I did everything correctly, the problem is not due to me neglecting the animal somehow. Specifically:

 * Chicken is allowed outside but it does not eat the grass. It walks through the grass, so it's not an issue with the grass being too far away, but the chicken will not actually eat it. The grass does not disappear as it would if it had been eaten.
 * Hay left out on the trough (yes, moved from the hopper to the trough) will disappear overnight as though it had been eaten, yet the animal is still thin the next morning. The hay always disappears even with the animal outside with grass, presumably because of the above point.
 * The chicken is petted every day and allowed outside, and even going to bed well before 6pm the animal will be grumpy the next day.
 * The chicken does lay eggs, so it's recognizing that the chicken ate, but it's still thin and grumpy each day.

I can do any additional testing needed, just let me know.

**Comment by vaindil** [comment]
I was able to test just now. I removed NSDR and the animal issue is fixed.

**Comment by Platonymous** [comment]
So it is only NSDR and not PYTK ?

**Comment by vaindil** [comment]
Correct. I removed NSDR and left PYTK when I tested and animals worked properly.

**Comment by Platonymous** [comment]
asimovic PR #18  might have fixed this. Update to the newest versions of PyTK (0.6.6) and NSDR (1.3.1)
