### ISSUE TITLE
Missing Source Code for Pelican TTS 1.13.2

### ISSUE THREAD

**Issue by croemmich** [Platonymous/Stardew-Valley-Mods#147]
I was hoping to update Pelican TTS to support 1.6, however it appears the source code for the latest release (1.13.2) is missing and the code in the repo doesn't compile.

**Comment by croemmich** [comment]
#148 updates to stardew1.6 from the code currently in the repo (1.13.1)

It still won't compile without AWSHandler, which should probably be included in the repo without the AWS credentials.

**Comment by Platonymous** [comment]
`AWSHandler` already only includes the credentials. it's only method `getPollyClient()` returns a `AmazonPollyClient` instance via
`new AmazonPollyClient("..accessKey...", "...secretKey...", Amazon.RegionEndpoint.USEast1)` and does nothing else.
