### ISSUE TITLE
Issue with Unknown Origin

### ISSUE THREAD

**Issue by Tithonius** [Platonymous/Stardew-Valley-Mods#24]
Recently i posted this issue on the SMAPI forums, and they told me that it was a crash with PYTK, after a more careful examination i did realize that the crashes do seem to be being caused by PYTK. The crashes seem to be occurring after i go out and do a normal day in the world, and then come back and go to sleep. The game fades to black, and before it can show me my profits, or save the game, the whole thing crashes. I would love if you could take a closer look at the crash, and feel free to call me an idiot if its all my fault :p i have one link to a parsed crash, and another of a pastebin of the crash that just happened today. I have also posted this issue on the Forum page for PYTK as well as on the issues section on the Nexus. would love some insight in to what is really going on.

https://log.smapi.io/KJtSD9mQ <--- This is the first crash that happened,

https://pastebin.com/7N8BT1w3 <--- And this is the crash that just happened today.

Any and all input is appreciated, and feel free to message me or post on the nexus forums or whatever if you need more information about the crash, or if you want me to run any kind of debugging.

Thanks, Tithonius

**Comment by Entoarox** [comment]
What mods are you using that require PyTK? Because one of those is causing the issue.
PyTK just isnt *reporting* that like it should....

**Comment by Tithonius** [comment]
Oh man, let me look over the modlist and see what all i have that uses Pytk

**Comment by Tithonius** [comment]
Well, i used your list on your nexus page to install the mods i wanted, and now looking at it, i have Animal Husbandry installed, Cobalt, Custom Farming Redux, No Soil Decay Redux, Seed Bag, and The Hard of Yoba Redux

**Comment by Tithonius** [comment]
and the crash is happening when i sleep

**Comment by Tithonius** [comment]
for custom farming redux i have Enchanting Table, Faberge Bench, Jewl Crafting Machines, Platonymous Examples, Platonymous Mailbox, Platonymous Mystical, Platonymous New Machines, Platonymous Signs, Reverse Transmutation, and Mutation Machines

**Comment by Tithonius** [comment]
i see from your reference that it may be the no soil decay redux causing the issue?

**Comment by Tithonius** [comment]
yes, after removing No Soil Decay Redux, i can confirm that it was the cause of the issue. Super annoying bug if i do say so myself, would love to use it, but i can live without.

**Comment by Platonymous** [comment]
Fixed in the latest version of NSDR
