### ISSUE TITLE
CostumFarming

### ISSUE THREAD

**Issue by AmburrBambii** [Platonymous/Stardew-Valley-Mods#6]
When creating a "Special Produce" the game and or mod does not respond properly to names that are 2 words: "Essential Oil" or words with multiple capital letters: "EssentialOil". When this happens, the "produceID" will revert to what is located on the springobjects.png and will not show up as the object from the custom sprite sheet.

All produce and machines need to be on a sprite sheet that is in a straight line as that is the only way it will read the tilesheet.

None of the machines or produce show up in the Item Spawner created by CJB. This is really only a hindrance for mod testing abilities.

I would also like for there to be more than one way to get different qualities to appear. So far it's either one or none. Adding in starred produce does not affect the outcome at all.

**Comment by Platonymous** [comment]
Custom Farming was replaced by Custom Farming Redux, which takes care of these issues, except for CJB, that's still not possible.
